### ISSUE TITLE
Wrong validation URL?

### ISSUE THREAD

**Issue by AntonBelousov** [AppsFlyerSDK/appsflyer-apple-purchase-connector#15]
Hello, I'm going to use your framework to automatically collect data about in-app purchases and subscriptions

I configured it as described in Readme file. When I tested it I received this error message:

`
[DEBUG] AppDelegate.swift didReceivePurchaseRevenueValidationInfo(_:error:) [38] Optional(Error Domain=com.appsflyer.sdk.network Code=40 "Network failure" UserInfo={NSLocalizedDescription=Network failure, NSUnderlyingError=0x282ef3d20 {Error Domain=com.appsflyer.sdk.network Code=0 "Request failed" UserInfo={NSLocalizedDescription=Request failed, NSUnderlyingError=0x282edfb70 {Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x282ef3cf0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo=0x282036b80 (not displayed)}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <2CE40225-5D45-4548-B888-1E4E5334637F>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(    "LocalDataTask <2CE40225-5D45-4548-B888-1E4E5334637F>.<2>"), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://(null)ars.(null)/api/v2/ios/validate_subscription<…>
`

I can't send it whole, as it cropped by console.app, but you can see the reason is in wrong URL (I'm pretty sure)
What can I do to fix this?

**Comment by VahanLab** [comment]
@af-obodovskyi could you please give us some feedbacks on that one?
I don't see the point of pushing tools if they're not maintained.
