### ISSUE TITLE
iOS Unity Build Fails Due to Conflicting Pods in AppsFlyer Purchase Connector and Strict Framework

### ISSUE THREAD

**Issue by tedo135** [AppsFlyerSDK/appsflyer-apple-purchase-connector#18]
Environment
Unity version: 2022.3.13f
AppsFlyer SDK version: 6.12.2
AppsFlyer Purchase Connector version: 6.12.2
Platform: iOS
Description
We are attempting to integrate the AppsFlyer Purchase Connector with the AppsFlyer Strict Framework in a Unity project targeted for iOS. However, we are encountering issues with the Pod installation process. The Unity Editor fails to build, citing a failed pod install command.

Steps to Reproduce
1. Set up a Unity project with AppsFlyer Purchase Connector and AppsFlyer Strict Framework.
2. Attempt to build for iOS.
3. Observe the pod installation failure.

Error: 
```
[!] The ‘Pods-UnityFramework’ target has frameworks with conflicting names: appsflyerlib.xcframework.
``` 
Additional Context
It appears the conflict arises because the AppsFlyer Purchase Connector iOS Pod has a dependency on AppsFlyerFramework, and since our project also requires AppsFlyerFramework/Static, both dependencies are installed, leading to a conflict. We are looking for guidance on how to resolve this issue.

Our Pod File:
[Podfile.txt](https://github.com/AppsFlyerSDK/appsflyer-apple-purchase-connector/files/13634530/Podfile.txt)
![Screenshot 2023-12-11 at 13 49 33](https://github.com/AppsFlyerSDK/appsflyer-apple-purchase-connector/assets/89385512/7a1104d7-d44d-400e-a23b-79490485505c)
![Screenshot 2023-12-11 at 13 48 14](https://github.com/AppsFlyerSDK/appsflyer-apple-purchase-connector/assets/89385512/042eb265-b148-4fe0-81de-dfc2c52a7b05)

**Comment by af-obodovskyi** [comment]
@tedo135 In order to integrate PC with Strict AppsFlyerSDK dependency using cocoapods, please try to use `pod PurchaseConnector/Strict`
