### ISSUE TITLE
AppsFlyer SDK 6.13.2

### ISSUE THREAD

**Issue by devibrahimkarahan** [AppsFlyerSDK/appsflyer-apple-purchase-connector#19]
Do you have a plan to upgrade the SDK to 6.13.2 ? We need to use AppsFlyer SDK 6.13.2 but we cant use it because Purchase Connectors pod version has 6.13.1 support

**Comment by VahanLab** [comment]
Same request but for AppsFlyer SDK 6.14+ (containing Privacy Manifest).

**Comment by CarlosModinez** [comment]
I believe we all will need this version 6.14+ with the Privacy Manifest file 🤕

**Comment by af-obodovskyi** [comment]
@devibrahimkarahan , @VahanLab , @CarlosModinez please check latest Purchase Connector release v6.14.3.
