### ISSUE TITLE
Purchase Connector SDK v6.15.0

### ISSUE THREAD

**Issue by galipMNL** [AppsFlyerSDK/appsflyer-apple-purchase-connector#20]
According to the [release notes](https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-release-notes) of AppsFlyer SDK v6.15.0 we have to update the Purchase Connector to version v6.15.0 in order to continue using the Purchase Connector with the latest version of the AppsFlyer SDK.

> Apps that use the Purchase Connector and update to this SDK release must also update their Purchase Connector to v6.15.0.

However v6.15.0 of the Purchase Connector is not available via SPM. Can this be made available?

**Comment by af-obodovskyi** [comment]
@galipMNL we do not have PurchaseConnector version supporting 6.15.0 version of the SDK. Last week we have released v6.15.2 of AppsFlyerSDK and Purchase Connector, please consider using it.
