### ISSUE TITLE
Crash after install the connecter v6.14.3

### ISSUE THREAD

**Issue by karltai0528** [AppsFlyerSDK/appsflyer-apple-purchase-connector#23]
I am using appsflyer v6.14.2 installed by SPM, I also tried to use 6.14.0 to 6.15.2, the app always crash, below is the screenshot of error.

<img width="915" alt="Screenshot 2024-12-10 at 5 33 12 PM" src="https://github.com/user-attachments/assets/a7729849-5a13-4d8f-81a5-7ebe147bd00a">

<img width="749" alt="Screenshot 2024-12-10 at 5 33 58 PM" src="https://github.com/user-attachments/assets/2c59b90b-5561-4c43-9c42-32a7bb4090ec">

**Comment by karltai0528** [comment]
```
dyld[5657]: Symbol not found: _OBJC_CLASS_$_AppsFlyerLib
  Referenced from: <0A542797-E558-3771-ABF6-84BE105BDC68> /private/var/containers/Bundle/Application/58D91141-2B47-4F02-B9CD-76367C2F0916/WSJ.app/Frameworks/PurchaseConnector.framework/PurchaseConnector
  Expected in:     <0315DBD1-AC12-3350-9A9E-F82BC625AD03> /private/var/containers/Bundle/Application/58D91141-2B47-4F02-B9CD-76367C2F0916/WSJ.app/Frameworks/AppsFlyerLib.framework/AppsFlyerLib
```
The above is the local log of the crash, [dyld](http://en.wikipedia.org/wiki/Dyld) errors are caused by a missing or a bad library linking, please check the issue.

**Comment by af-obodovskyi** [comment]
@karltai0528 checking

**Comment by karltai0528** [comment]
@af-obodovskyi Yes, I did, same error occurs. But the app won't crash by using 6.13.1 or below

**Comment by karltai0528** [comment]
@af-obodovskyi  FYI, I'm using xcode 15.4

**Comment by af-obodovskyi** [comment]
@karltai0528 I have managed to reproduce the issue. 
The problem is in `Static` AppsFlyerLib dependency.  
While we are fixing the issue, the temporary solution for you might be using [AppsFlyerLib-Dynamic](https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic)

**Comment by karltai0528** [comment]
@af-obodovskyi The issue has been fixed by not using Appsflyer-dynamic, thank you
