### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by valpio-ios** [AppsFlyerSDK/appsflyer-apple-purchase-connector#5]
Throws an error when running app from Xcode 13.2.1 
`Undefined symbols for architecture arm64:
  "_objc_msgSend$type", referenced from:
      -[AFSDKProduct initWithProduct:transactionId:transactionStatus:originalTransactionId:] in PurchaseConnector(AFSDKProduct.o)
  "_objc_msgSend$priceLocale", referenced from:
      -[AFSDKProduct initWithProduct:transactionId:transactionStatus:originalTransactionId:] in PurchaseConnector(AFSDKProduct.o)
  "_objc_msgSend$numberOfPeriods", referenced from:
      -[AFSDKProduct initWithProduct:transactionId:transactionStatus:originalTransactionId:] in PurchaseConnector(AFSDKProduct.o)
  "_objc_msgSend$unit", referenced from:
      -[AFSDKProduct initWithProduct:transactionId:transactionStatus:originalTransactionId:] in PurchaseConnector(AFSDKProduct.o)`

and many more like this

**Comment by af-obodovskyi** [comment]
@valpio-ios please, check v6.10.1 of the connector, your issue should be solved.
